on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Suffix (app will be named iopay-{suffux}.apk)'
        required: false 
        type: string
        
jobs:
  print-tag:
    runs-on: ubuntu-latest
#     if:  ${{ github.event.inputs.print_tags == 'true' }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.tags }} 
        
      - if: ${{ github.event.inputs.tags == '' }}
        run: |
          APK_NAME=iopay-master.apk
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
    
      - if: ${{ github.event.inputs.tags != '' }}
        run: |
          APK_NAME=iopay-${{ github.event.inputs.tags }}.apk
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
        
      - run: echo ${{ env.APK_NAME }}
